/** @format */

import { NextResponse } from "next/server";
import { getDb } from "../../../lib/mongodb";
import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, phone, service, message } = body;

    // Validation
    if (!name || !email || !message) {
      return NextResponse.json(
        { success: false, message: "Name, email, and message are required." },
        { status: 400 },
      );
    }
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { success: false, message: "Invalid email address." },
        { status: 400 },
      );
    }

    const db = await getDb();

    // 1. Insert lead into MongoDB
    const lead = {
      name,
      email,
      phone: phone || "",
      service: service || "other",
      message,
      status: "NEW",
      createdAt: new Date(),
    };
    await db.collection("leads").insertOne(lead);

    // 2. Send notification email via Resend
    await resend.emails.send({
      from: "SetupGram <onboarding@resend.dev>",
      to: "info@setupgram.com",
      subject: `🚀 New Lead: ${name} — ${service || "General Inquiry"}`,
      html: `
        <div style="font-family:sans-serif;max-width:600px;margin:0 auto;background:#050505;color:#e2e8f0;padding:32px;border-radius:12px;border:1px solid rgba(0,240,255,0.2)">
          <h2 style="color:#00f0ff;margin-bottom:24px">New Lead from SetupGram</h2>
          <table style="width:100%;border-collapse:collapse">
            <tr><td style="padding:8px 0;color:#94a3b8;width:120px">Name</td><td style="padding:8px 0;color:#fff;font-weight:600">${name}</td></tr>
            <tr><td style="padding:8px 0;color:#94a3b8">Email</td><td style="padding:8px 0"><a href="mailto:${email}" style="color:#00f0ff">${email}</a></td></tr>
            <tr><td style="padding:8px 0;color:#94a3b8">Phone</td><td style="padding:8px 0;color:#fff">${phone || "—"}</td></tr>
            <tr><td style="padding:8px 0;color:#94a3b8">Service</td><td style="padding:8px 0;color:#b026ff;font-weight:600;text-transform:uppercase">${service || "—"}</td></tr>
            <tr><td style="padding:8px 0;color:#94a3b8;vertical-align:top">Message</td><td style="padding:8px 0;color:#e2e8f0;line-height:1.6">${message}</td></tr>
          </table>
          <div style="margin-top:32px;padding-top:24px;border-top:1px solid rgba(255,255,255,0.1)">
            <a href="https://setupgram.com/admin/leads" style="display:inline-block;padding:12px 24px;background:#00f0ff;color:#050505;font-weight:700;border-radius:8px;text-decoration:none">View in Admin Panel →</a>
          </div>
          <p style="color:#475569;font-size:12px;margin-top:24px">This email was auto-generated by SetupGram CRM.</p>
        </div>
      `,
    });

    return NextResponse.json(
      {
        success: true,
        message: "Message received. We'll be in touch shortly.",
      },
      { status: 200 },
    );
  } catch (error) {
    console.error("Contact form error:", error);
    return NextResponse.json(
      { success: false, message: "Internal server error." },
      { status: 500 },
    );
  }
}
